spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql9.hekko.net.pl
    username: kristoff_engageadm
    password: engageadmin

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

flyway:
  schemas: kristoff_engage

taxes:
  vat:
    uk: 0.20


